import { Info } from "lucide-react";

export function ResponsibleAiDisclaimer() {
  return (
    <div className="border-t border-border/60 bg-card/40 px-4 py-3 text-xs text-muted-foreground">
      <div className="mx-auto flex max-w-6xl items-start gap-2">
        <Info className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" />
        <p className="min-w-0">
          <span className="font-medium text-foreground">Responsible AI notice:</span> Outputs are
          generated by AI and may be inaccurate or biased. Always review before use. This app does
          not store your prompts, outputs, or credentials on any server — reviews are kept only in
          your browser.
        </p>
      </div>
    </div>
  );
}
